version: 3

tasks:
  default:
    cmds:
      - task: test
  
  test:
    cmds:
      - odin test unthread
    sources:
      - unthread/**/*.odin
    aliases:
      - t
    method: none
    silent: true

interval: 250ms
