version: 3

tasks:
  default:
    cmds:
      - task: test

  build:
    cmds:
      - odin build unthread -o:speed -out:./bin/unthread
    sources:
      - ./**/*.odin
    generates:
      - ./bin/unthread
    aliases:
      - b
    silent: true
  
  test:
    cmds:
      - task: test_unthread
      - task: test_cli
    aliases:
      - t
    method: none
    silent: true

  test_unthread:
    cmds:
      - odin test unthread
    sources:
      - ./unthread/**/*.odin
    aliases:
      - tunthread
    method: none
    silent: true

  test_cli:
    cmds:
      - odin test cli
    sources:
      - ./cli/**/*.odin
    aliases:
      - tcli
    method: none
    silent: true

  clean:
    cmds:
      - rm -rf ./bin
    aliases:
      - c
    silent: true

interval: 250ms
