version: 3

vars:
  COLLECTION: -collection:dependencies=dependencies

tasks:
  default:
    cmds:
      - task: test

  build:
    cmds:
      - odin build unthread -o:speed -out:./bin/unthread {{.COLLECTION}}
    sources:
      - ./**/*.odin
    generates:
      - ./bin/unthread
    aliases:
      - b
    silent: true
  
  test:
    cmds:
      - task: test_unthread
    aliases:
      - t
    method: none
    silent: true

  test_unthread:
    cmds:
      - odin test unthread {{.COLLECTION}}
    sources:
      - ./unthread/**/*.odin
    aliases:
      - tunthread
    method: none
    silent: true

  clean:
    cmds:
      - rm -rf ./bin
    aliases:
      - c
    silent: true

interval: 250ms
