version: 3

tasks:
  default:
    cmds:
      - task: test

  build:
    cmds:
      - odin build unthread -o:speed -out:./bin/unthread
    sources:
      - unthread/**/*.odin
    generates:
      - ./bin/unthread
    aliases:
      - b
    silent: true
  
  test:
    cmds:
      - odin test unthread
    sources:
      - unthread/**/*.odin
    aliases:
      - t
    method: none
    silent: true

  clean:
    cmds:
      - rm -rf ./bin
    aliases:
      - c
    silent: true

interval: 250ms
