name: build-and-maybe-upload-release

on:
  push:
    # Build on push to `main`
    branches:
      - main
    # Build release only when a tag is created starting with "v"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: gonz/odin:latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir bin
          odin build unthread -o:speed -out:./bin/unthread -collection:dependencies=dependencies
      - name: Create release if we are on version tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/unthread
          replacesArtifacts: true
